### Login
POST http://localhost:8000/api/auth/login
Content-Type: application/json

{
    "email": "testuser@test.com",
    "password": "abcd@1234"
}

### Test to see login response
GET http://localhost:8000/api/auth/login

### Protected endpoint request
@authToken = {{login.response.body.token}} // Assuming the login response includes a token field
GET http://localhost:8000/api/protected-endpoint/
Authorization: Bearer {{authToken}}

### Refresh Token
POST http://localhost:8000/api/auth/refresh
Content-Type: application/json

{
    "refresh_token": "your_refresh_token_here"
}